site_name: Tufts Research Technology Bioinformatics
site_url: https://rt.bio.io

theme:
    name: material
    logo: 'img/newlogo.png'

    features:
        - navigation.sections
        - navigation.tabs.sticky
        - navigation.tabs
extra_css:
    - stylesheets/extra.css

nav:
    - About : about/about.md
    - HPC User Guide : hpc-user-guide/hpc-user-guide.md
    - Data & Storage
