site_name: Tufts Research Technology Bioinformatics
repo_url: https://github.com/BioNomad/tuftsTutorials

theme:
  name: material
  features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
  logo: 'img/newlogo.png'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
extra_css:
    - stylesheets/extra.css

nav:
    - About : index.md
    - HPC User Guide : 
        - Introduction To The Cluster:
            - "What Is The Cluster?": hpc-user-guide/what-is-the-cluster.md
            - "Request an Account": hpc-user-guide/request-account.md
            - "Navigate To The Cluster": hpc-user-guide/navigate-to-cluster.md
            - "File Transfer": hpc-user-guide/file-transfer.md
        - Cluster Resources:
            - "HPC Storage": hpc-user-guide/hpc-storage.md
            - "Compute Resources": hpc-user-guide/compute-resources.md
            - "Software On The Cluster": hpc-user-guide/software-cluster.md
        - Introduction To SLURM:
            - "Interactive Session": hpc-user-guide/interactive-session.md
            - "Submitting A Batch Job": hpc-user-guide/batch-job.md
            - "Checking Job Status": hpc-user-guide/job-status.md
    - Software Tutorials:
        - Intro To Unix:
            - "Introduction To Unix" : tutorials/intro-to-unix/unix.md
        - Intro To R: 
            - "Introduction To R OnDemand": tutorials/intro-to-r/r-ondemand.md
            - "The Basics": tutorials/intro-to-r/basics.md
            - "Data Structures": tutorials/intro-to-r/data-structures.md
            - "Functions & Flow": tutorials/intro-to-r/functions-flow.md
            - "Inspecting/Manipulating Data": tutorials/intro-to-r/inspecting-manipulating-data.md
            - "Visualization": tutorials/intro-to-r/visualization.md
        - Intro To Python:
            - "Introduction To Python OnDemand": tutorials/intro-to-python/python-ondemand.md
            - "Variables & Data Types": tutorials/intro-to-python/variables-data-types.md
            - "Libraries & Data Frames": tutorials/intro-to-python/libraries-data-frames.md
            - "Plotting with Plotly": tutorials/intro-to-python/plotting-plotly.md
            - "Lists": tutorials/intro-to-python/lists.md
            - "Loops & Conditionals": tutorials/intro-to-python/loops-conditionals.md
            - "Functions & Scope": tutorials/intro-to-python/functions-scope.md
    - Omics Tutorials:
        - Intro To 16S Metabarcoding: 
            - "Background": omics/intro-to-16S/background.md
            - "Setup": omics/intro-to-16S/setup.md
            - "Quality Control": omics/intro-to-16S/quality-control.md
        
