site_name: Tufts Research Technology Bioinformatics
site_url: https://rt.bio.io

theme:
    name: material
    logo: 'img/newlogo.png'
    
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections

extra_css:
    - stylesheets/extra.css

nav:
    - About : index.md
    - HPC User Guide : 
        - "What Is The Cluster?": hpc-user-guide/what-is-the-cluster.md
        - "Request an Account": https://access.tufts.edu/research-cluster-account
        - "Navigate To The Cluster": hpc-user-guide/navigate-to-cluster.md
    - Tutorials:
        - Intro To R: 
            - "Introduction To R OnDemand": tutorials/intro-to-r/r-ondemand.md
            - "Project Management": tutorials/intro-to-r/project-management.md
            - "Data Structures": tutorials/intro-to-r/data-structures.md
            - "Data Frames": tutorials/intro-to-r/data-frames.md
            - "Subsetting": tutorials/intro-to-r/subsetting.md
            - "Visualization": tutorials/intro-to-r/visualization.md
